server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/files_mananger?useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: Icanfly_8686
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    #开启mybatis-plus sql 日志
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # update-strategy: not_empty
      # 删除前
      logic-not-delete-value: 0
      # 删除后
      logic-delete-value: 1
      # ID默认生成策略
      id-type: auto
# 日志配置
logging:
  level:
    com.files: debug